
utils::globalVariables(c("% Adult Height",
                         "Age",
                         "Age * Leg Length",
                         "Age * Sitting Height",
                         "Age * Weight",
                         "Age @ PHV",
                         "Age2",
                         "Agemos",
                         "Athlete",
                         "Athlete.fact",
                         "B1",
                         "B2",
                         "Bench Height (CM)",
                         "Birth Year",
                         "CV",
                         "Current Age",
                         "Date of Birth",
                         "Diferenca",
                         "Error (CM)",
                         "Error (IN)",
                         "Estimated Adult Height (CM)",
                         "Estimated Adult Height (IN)",
                         "F-Height",
                         "F-Midparent Stature",
                         "F-Weight",
                         "Fathers Height (CM)",
                         "Gender",
                         "Height (CM)",
                         "Height (IN)",
                         "Height1 (CM)",
                         "Height2 (CM)",
                         "Leg Length (CM)",
                         "Leg Length * Sitting Height",
                         "M-Height",
                         "M-Midparent Stature",
                         "M-Weight",
                         "Maturity Offset (years)",
                         "Median",
                         "Metric",
                         "Mothers Height (CM)",
                         "P10",
                         "P25",
                         "P3",
                         "P5",
                         "P50",
                         "P75",
                         "P90",
                         "P95",
                         "P97",
                         "Parent Mid Height (CM)",
                         "Parent Mid Height (IN)",
                         "Power",
                         "Quarter",
                         "Remaining Growth (CM)",
                         "Remaining Growth (IN)",
                         "Sitting Height (CM)",
                         "Sitting Height1 (CM)",
                         "Sitting Height2 (CM)",
                         "Stages",
                         "Testing Date",
                         "Type",
                         "Value",
                         "W-H Ratio",
                         "Weight (KG)",
                         "Weight (LB)",
                         "Weight1 (KG)",
                         "Weight2 (KG)",
                         "Years",
                         "aes",
                         "annotate",
                         "arrange",
                         "desc",
                         "element_blank",
                         "element_line",
                         "element_rect",
                         "element_text",
                         "everything",
                         "gather",
                         "geom_curve",
                         "geom_line",
                         "geom_point",
                         "geom_rect",
                         "geom_ribbon",
                         "geom_segment",
                         "geom_text",
                         "geom_vline",
                         "ggplot",
                         "ggtitle",
                         "labs",
                         "mutate",
                         "na.omit",
                         "reorder",
                         "scale_color_manual",
                         "scale_fill_manual",
                         "scale_x_continuous",
                         "select",
                         "theme",
                         "theme_light",
                         "unit",
                         "xlab",
                         "xlim",
                         "xmax",
                         "xmin",
                         "ylab",
                         "ylim",
                         "ymax",
                         "ymin"))
